<?php

namespace WorkActivityBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class BaseController extends Controller
{
    public function addFlash($type, $message)
    {
        parent::addFlash($type, $message); // TODO: Change the autogenerated stub
    }

    public function getEM()
    {
        return $this->getDoctrine()->getManager();
    }
}
